[package]
name = "accounting"
version = "0.1.0"
edition = "2024"

[dependencies]

# async, web
tokio = { version="1.47.1", features=["full"] }
reqwest = { version = "0.11.16", features=["json"] }
futures = "^0.3"
hyper = { version = "1.7.0", features = ["full"] }
http = "0.2"
http-body-util = "0.1.3"
hyper-util = {version="0.1.16", features=["tokio"]}
# codecs, formats
serde = { version="1.0.159", features=["derive"] }
serde_json = "1.0.95"
chrono = { version="0.4.24", features=["serde"] }
rust_decimal = { version="^1.35", features=["maths"]}
num-traits = "^0.2"
# config, errors
anyhow = "^1.0"
thiserror = "^1.0"
async-trait = "0.1.68"
backtrace = "0.3.67"
rand = "^0.8"
# own libs
file-cache = { git="ssh+git://git@github.com/nmrshll/rust-libs" }
uuid = { version = "1.18.0", features = ["v4"] }
url = "2.5.4"
urlencoding = "2.1.3"
base64 = "0.22.1"
# serde_urlencoded = "0.7.1"

# api-client-utils = { git="ssh+git://git@github.com/nmrshll/rust-libs" }
# num-traits = "0.2.19"
[patch.'ssh://git@github.com/nmrshll/rust-libs']
file-cache = { path = "../rust-libs/file-cache" }
