[workspace]
members = ["apps/*", "libs/*"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "^1.53", features = ["full"] }
reqwest = { version = "0.13.4", features = ["json", "query"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
serde_json_lenient = "0.2.4"
chrono = { version = "0.4.45", features = ["serde"] }
anyhow = { version = "^1.0" }
thiserror = { version = "^1.0" }
snafu = { version = "^0.8" }
async-trait = { version = "0.1.91" }
uuid = { version = "1.24.0" }
base64 = { version = "0.23.1" }
futures = { version = "^0.3" }
rucash = { version = "0.7" }
