#!/usr/bin/env bash
if [ ! -n "${TMUX:-}" ]; then set -euxo pipefail; fi
export wd=$(cd $(dirname $(dirname "$0")); pwd -P)
export wdname=$(basename ${wd})
cd "$wd"

if which direnv ; then direnv status | grep "Found RC allowed true" || direnv allow; fi

# make dirs
if [ ! -d "$wd/.cache" ]; then mkdir -p "$wd/.cache"; fi


# auto configure vs-code/rust-analyzer to work with nix 
if [ "$(which code)" = "/usr/local/bin/code" ]; then 
    SETTINGS_PATH="${wd}/.vscode/settings.json"; mkdir -p $(dirname "$SETTINGS_PATH");
    ORIGINAL_SETTINGS=$(if [ -s "$SETTINGS_PATH" ]; then cat "$SETTINGS_PATH"; else echo "{}"; fi)
    echo "$ORIGINAL_SETTINGS" \
        | jq ".\"rust-analyzer.server.extraEnv\".\"CARGO\" |= \"$(which cargo)\"" \
        | jq ".\"rust-analyzer.server.extraEnv\".\"RUSTC\" |= \"$(which rustc)\""  \
        | jq ".\"rust-analyzer.server.extraEnv\".\"RUSTFMT\" |= \"$(which rustfmt)\""  \
        >| "${wd}/.vscode/settings.json"
fi

loaddotenv() {
    if [ -f "${wd}/.env" ]; then 
        source "${wd}/.env"; 
        case "$(uname -s)" in
            Linux*)     echo "NOT SUPPORTED YET: sourcing .env on Linux" ;; # TODO
            Darwin*)    export export `cat "${wd}/.env" | grep -v -e '^#' -e '^[[:space:]]*$' | cut -d= -f1` ;;
        esac
    fi
}
loaddotenv



case "${1:-}" in 
    "banks")
        curl -X GET "https://ob.nordigen.com/api/v2/institutions/?country=gb" \
            -H  "accept: application/json" \
            -H  "Authorization: Bearer ${NORDIGEN_ACCESS_JWT}"
        ;;
    *);;
esac
