//! Toasty `#[derive(Model)]` definitions (spec §5).
//!
//! Every resource is owned by a `User`; ownership is enforced in the
//! handlers, never by the schema.
//!
//! Conventions:
//! - ids are UUID v7, auto-generated by toasty (`#[auto]` on a `uuid::Uuid`);
//! - timestamps/dates are RFC 3339 / ISO-8601 **strings** (the app clock
//!   writes them; they sort correctly in the DB and avoid a chrono/jiff
//!   dependency in this crate);
//! - `Ledger::*_count` keeps the ingest-time counts (a convenience for the
//!   JSON views; the ledger is always rebuilt for reports via
//!   `GnucashBook::from_raw_parts`, which recomputes balances from splits);
//! - `Account::balance` and `Split::value` are `rust_decimal::Decimal`
//!   (`rucash::Num` is a re-export of `rust_decimal::Decimal` under its
//!   `decimal` feature, which `ixbrl` enables);
//! - list-shaped profile fields are `toasty::Json<…>` in a native Postgres
//!   `json` column.
//!
//! The models also derive `Serialize` (with the relation fields skipped), so
//! handlers can return them directly; ledger row views build their own JSON
//! shapes (see `ledgers.rs`).

use std::collections::HashMap;

use serde::Serialize;
use toasty::Model;

#[derive(Debug, Serialize, Model)]
pub struct User {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub email: String,
    #[serde(skip)]
    pub password_hash: String,
    pub display_name: String,
    /// RFC 3339 UTC.
    pub created_at: String,
    #[serde(skip)]
    #[has_many]
    pub sessions: toasty::Deferred<Vec<Session>>,
    #[serde(skip)]
    #[has_many]
    pub companies: toasty::Deferred<Vec<Company>>,
}

#[derive(Debug, Serialize, Model)]
pub struct Session {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub user_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = user_id, references = id)]
    pub user: toasty::Deferred<User>,
    /// sha256 of the bearer token (the plaintext is returned once, at login).
    #[serde(skip)]
    #[unique]
    pub token_hash: String,
    /// RFC 3339 UTC.
    pub created_at: String,
    /// RFC 3339 UTC.
    pub expires_at: String,
}

#[derive(Debug, Serialize, Model)]
pub struct Company {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub user_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = user_id, references = id)]
    pub user: toasty::Deferred<User>,

    // -- identity -----------------------------------------------------------
    pub name: String,
    /// Corporation Tax reference (UTR). May be blank when unknown at
    /// creation time.
    pub tax_reference: String,
    /// Companies House company number; blank when created by hand.
    pub company_number: String,
    /// ISO-8601 date (`YYYY-MM-DD`); optional.
    pub registration_date: Option<String>,

    // -- descriptive profile (optional; config wins over CH enrichment) ----
    #[column(type = json)]
    pub directors: toasty::Json<Vec<String>>,
    pub contact_name: Option<String>,
    #[column(type = json)]
    pub address_lines: toasty::Json<Vec<String>>,
    pub county: Option<String>,
    pub location: Option<String>,
    pub postcode: Option<String>,
    pub email: Option<String>,
    pub phone_country: Option<String>,
    pub phone_area: Option<String>,
    pub phone_number: Option<String>,
    pub website_url: Option<String>,
    pub website_description: Option<String>,
    pub vat_registration: Option<String>,
    #[column(type = json)]
    pub sic_codes: toasty::Json<Vec<String>>,
    pub activities: Option<String>,
    pub jurisdiction: Option<String>,
    pub accountant_name: Option<String>,
    pub accountant_business: Option<String>,
    pub accountant_address: Option<String>,
    pub auditor_name: Option<String>,
    pub auditor_business: Option<String>,
    pub auditor_address: Option<String>,
    pub industry_sector_dimension: Option<String>,
    pub legal_form_dimension: Option<String>,
    pub country_dimension: Option<String>,
    pub contact_country_dimension: Option<String>,
    pub phone_type_dimension: Option<String>,
    pub logo_b64: Option<String>,

    // -- accounts metadata (report generation inputs) -----------------------
    pub fy1_year: i32,
    pub fy2_year: i32,
    /// Number of associated companies excluding this one; `None` = standalone.
    pub associated_companies: Option<i32>,
    /// ISO-8601 dates (`YYYY-MM-DD`); the publication/authorisation dates
    /// cannot be inferred, so they are required for report generation.
    pub report_date: Option<String>,
    pub authorised_date: Option<String>,
    pub incorporation_date: Option<String>,
    /// Defaults to the first director at report time when absent.
    pub signed_by: Option<String>,
    #[column(type = json)]
    pub average_employees: Option<toasty::Json<HashMap<String, u32>>>,
    /// Base64-encoded director's signature ("" for none).
    pub signature_b64: Option<String>,

    #[serde(skip)]
    #[has_many]
    pub ledgers: toasty::Deferred<Vec<Ledger>>,
}

#[derive(Debug, Serialize, Model)]
pub struct Ledger {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub company_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = company_id, references = id)]
    pub company: toasty::Deferred<Company>,
    /// Original upload filename.
    pub name: String,
    /// Absolute path of the stored file under the uploads dir.
    pub file_path: String,
    pub file_sha256: String,
    /// RFC 3339 UTC.
    pub uploaded_at: String,
    pub accounts_count: i64,
    pub transactions_count: i64,
    pub splits_count: i64,
    #[serde(skip)]
    #[has_many]
    pub accounts: toasty::Deferred<Vec<Account>>,
    #[serde(skip)]
    #[has_many]
    pub transactions: toasty::Deferred<Vec<Transaction>>,
    #[serde(skip)]
    #[has_many]
    pub splits: toasty::Deferred<Vec<Split>>,
}

#[derive(Debug, Serialize, Model)]
pub struct Account {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub ledger_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = ledger_id, references = id)]
    pub ledger: toasty::Deferred<Ledger>,
    pub guid: String,
    pub name: String,
    #[serde(rename = "type")]
    pub account_type: String,
    pub parent_guid: String,
    /// Balance as a decimal string (kept in sync with the splits on ingest).
    pub balance: rust_decimal::Decimal,
}

#[derive(Debug, Serialize, Model)]
pub struct Transaction {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub ledger_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = ledger_id, references = id)]
    pub ledger: toasty::Deferred<Ledger>,
    pub guid: String,
    /// RFC 3339 UTC (converted from the book's `chrono::NaiveDateTime`).
    pub post_datetime: String,
    /// GnuCash transaction description/memo ("" when the book has none).
    pub description: String,
}

#[derive(Debug, Serialize, Model)]
pub struct Split {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub ledger_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = ledger_id, references = id)]
    pub ledger: toasty::Deferred<Ledger>,
    #[index]
    pub tx_guid: String,
    #[index]
    pub account_guid: String,
    /// Value as a decimal string.
    pub value: rust_decimal::Decimal,
}
