//! Toasty `#[derive(Model)]` definitions (spec §5).
//!
//! Every resource is owned by a `User`; ownership is enforced in the
//! handlers, never by the schema.
//!
//! Conventions:
//! - ids are UUID v7, auto-generated by toasty (`#[auto]` on a `uuid::Uuid`);
//! - timestamps/dates are RFC 3339 / ISO-8601 **strings** (the app clock
//!   writes them; they sort correctly in the DB and avoid a chrono/jiff
//!   dependency in this crate);
//! - `Ledger::*_count` keeps the ingest-time counts (a convenience for the
//!   JSON views; the ledger is always rebuilt for reports via
//!   `GnucashBook::from_raw_parts`, which recomputes balances from splits);
//! - `Account::balance` and `Split::value` are `rust_decimal::Decimal`
//!   (`rucash::Num` is a re-export of `rust_decimal::Decimal` under its
//!   `decimal` feature, which `ixbrl` enables);
//! - list-shaped profile fields are `toasty::Json<…>` in a native Postgres
//!   `json` column.
//!
//! The models also derive `Serialize` (with the relation fields skipped), so
//! handlers can return them directly; ledger row views build their own JSON
//! shapes (see `ledgers.rs`).

use std::collections::HashMap;

use serde::Serialize;
use toasty::Model;

#[derive(Debug, Serialize, Model)]
pub struct User {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub email: String,
    #[serde(skip)]
    pub password_hash: String,
    pub display_name: String,
    /// RFC 3339 UTC.
    pub created_at: String,
    /// True for guest rows (temp-user spec §4): a placeholder email + dummy
    /// hash, adopted in place by `POST /auth/register`.
    pub is_temporary: bool,
    /// The client-generated anonymous identity (`X-Guest-Id`); NULL for
    /// real users, cleared on adoption. DB unique index in 0003.
    #[unique]
    pub guest_id: Option<String>,
    #[serde(skip)]
    #[has_many]
    pub sessions: toasty::Deferred<Vec<Session>>,
    #[serde(skip)]
    #[has_many]
    pub companies: toasty::Deferred<Vec<Company>>,
}

#[derive(Debug, Serialize, Model)]
pub struct Session {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub user_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = user_id, references = id)]
    pub user: toasty::Deferred<User>,
    /// sha256 of the bearer token (the plaintext is returned once, at login).
    #[serde(skip)]
    #[unique]
    pub token_hash: String,
    /// RFC 3339 UTC.
    pub created_at: String,
    /// RFC 3339 UTC.
    pub expires_at: String,
}

#[derive(Debug, Serialize, Model)]
pub struct Company {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub user_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = user_id, references = id)]
    pub user: toasty::Deferred<User>,

    // -- identity -----------------------------------------------------------
    pub name: String,
    /// Corporation Tax reference (UTR). May be blank when unknown at
    /// creation time.
    pub tax_reference: String,
    /// Companies House company number; blank when created by hand.
    pub company_number: String,
    /// ISO-8601 date (`YYYY-MM-DD`); optional.
    pub registration_date: Option<String>,

    // -- descriptive profile (optional; config wins over CH enrichment) ----
    #[column(type = json)]
    pub directors: toasty::Json<Vec<String>>,
    pub contact_name: Option<String>,
    #[column(type = json)]
    pub address_lines: toasty::Json<Vec<String>>,
    pub county: Option<String>,
    pub location: Option<String>,
    pub postcode: Option<String>,
    pub email: Option<String>,
    pub phone_country: Option<String>,
    pub phone_area: Option<String>,
    pub phone_number: Option<String>,
    pub website_url: Option<String>,
    pub website_description: Option<String>,
    pub vat_registration: Option<String>,
    #[column(type = json)]
    pub sic_codes: toasty::Json<Vec<String>>,
    pub activities: Option<String>,
    pub jurisdiction: Option<String>,
    pub accountant_name: Option<String>,
    pub accountant_business: Option<String>,
    pub accountant_address: Option<String>,
    pub auditor_name: Option<String>,
    pub auditor_business: Option<String>,
    pub auditor_address: Option<String>,
    pub industry_sector_dimension: Option<String>,
    pub legal_form_dimension: Option<String>,
    pub country_dimension: Option<String>,
    pub contact_country_dimension: Option<String>,
    pub phone_type_dimension: Option<String>,
    pub logo_b64: Option<String>,

    // -- accounts metadata (report generation inputs) -----------------------
    /// The accounting standard the web add dialog collects: `FRS 105` (micro-
    /// entities, default) or `FRS 102`.
    pub accounting_standard: String,
    /// RFC 3339 UTC — last write (create / PATCH / enrich). The guest sweep's
    /// activity clock (temp-user spec §8); NULL for pre-0003 rows.
    pub updated_at: Option<String>,
    pub fy1_year: i32,
    pub fy2_year: i32,
    /// Number of associated companies excluding this one; `None` = standalone.
    pub associated_companies: Option<i32>,
    /// ISO-8601 dates (`YYYY-MM-DD`); the publication/authorisation dates
    /// cannot be inferred, so they are required for report generation.
    pub report_date: Option<String>,
    pub authorised_date: Option<String>,
    pub incorporation_date: Option<String>,
    /// Defaults to the first director at report time when absent.
    pub signed_by: Option<String>,
    #[column(type = json)]
    pub average_employees: Option<toasty::Json<HashMap<String, u32>>>,
    /// Base64-encoded director's signature ("" for none).
    pub signature_b64: Option<String>,

    #[serde(skip)]
    #[has_many]
    pub ledgers: toasty::Deferred<Vec<Ledger>>,
}

/// A durable background job (spec: ch-filings-sync-spec.md §3). The worker
/// claims `pending` rows (`SELECT … FOR UPDATE SKIP LOCKED`), flips them to
/// `running` for their execution, and records `done`/`failed` + `last_error`.
/// `attempts` / `next_retry_at` are written but unused today (fail-fast
/// policy; reserved for a future backoff).
#[derive(Debug, Serialize, Model)]
pub struct Job {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    /// Job kind, e.g. `fetch_filings`.
    pub kind: String,
    #[index]
    pub company_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = company_id, references = id)]
    pub company: toasty::Deferred<Company>,
    /// `pending` | `running` | `done` | `failed`.
    pub status: String,
    pub attempts: i32,
    pub last_error: Option<String>,
    /// RFC 3339 UTC (reserved for the future retry policy).
    pub next_retry_at: Option<String>,
    /// RFC 3339 UTC.
    pub created_at: String,
    /// RFC 3339 UTC.
    pub updated_at: String,
}

/// A Companies House form type code (e.g. `AA` accounts, `CS01` confirmation
/// statement).  Known codes are modelled; any other code is preserved
/// verbatim so unknown filings round-trip.
///
/// Stored by toasty as an embedded enum: the `form_type` discriminant column
/// (Postgres `ch_form_type` enum type) plus a nullable `form_type_code`
/// payload column holding the raw code for the [`Self::Other`] variant.
#[derive(Debug, Clone, PartialEq, Eq, toasty::Embed)]
pub enum ChFormType {
    /// Annual accounts (`AA`).
    Accounts,
    /// Change of accounting reference date (`AA01`).
    ChangeAccountingReferenceDate,
    /// Confirmation statement (`CS01`).
    ConfirmationStatement,
    /// Change of registered office address (`AD01`).
    ChangeRegisteredOffice,
    /// Incorporation (`NEWINC`).
    Incorporation,
    /// Any other form type code, preserved verbatim.
    Other { code: String },
}

impl ChFormType {
    /// Parse a Companies House form type code; codes without a modelled
    /// variant are preserved verbatim in [`Self::Other`].
    ///
    /// The code table lives in `ct600` ([`ct600::companies_house::FormType`]);
    /// this storage enum collapses its finer account-family granularity
    /// (micro-entity / dormant …) into [`Self::Accounts`] and maps the rest
    /// 1:1.
    pub fn from_code(code: &str) -> Self {
        use ct600::companies_house::FormType;
        match FormType::from_code(code) {
            FormType::Accounts
            | FormType::MicroEntityAccounts
            | FormType::DormantAccounts => Self::Accounts,
            FormType::ChangeAccountingReferenceDate => Self::ChangeAccountingReferenceDate,
            FormType::ConfirmationStatement => Self::ConfirmationStatement,
            FormType::ChangeRegisteredOffice => Self::ChangeRegisteredOffice,
            FormType::Incorporation => Self::Incorporation,
            _ => Self::Other {
                code: code.to_string(),
            },
        }
    }

    /// The raw Companies House code, e.g. `AA` or `TM01`.
    pub fn as_code(&self) -> &str {
        match self {
            Self::Accounts => "AA",
            Self::ChangeAccountingReferenceDate => "AA01",
            Self::ConfirmationStatement => "CS01",
            Self::ChangeRegisteredOffice => "AD01",
            Self::Incorporation => "NEWINC",
            Self::Other { code } => code,
        }
    }
}

/// Serialize as the raw code string (the web UI shows `AA` / `CS01` …).
impl serde::Serialize for ChFormType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_code())
    }
}

impl<'de> serde::Deserialize<'de> for ChFormType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let code = String::deserialize(deserializer)?;
        Ok(Self::from_code(&code))
    }
}

/// A single Companies House filing-history item, persisted for the company
/// (spec: ch-filings-sync-spec.md §1). Idempotent re-fetch upserts on
/// `(company_id, ch_transaction_id)`.
#[derive(Debug, Serialize, Model)]
pub struct Filing {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub company_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = company_id, references = id)]
    pub company: toasty::Deferred<Company>,
    /// The CH transaction id (parsed from the item's `links.self`).
    pub ch_transaction_id: String,
    /// Filing category, e.g. `accounts`, `confirmation-statement`.
    pub category: String,
    /// Form type code, e.g. `AA`, `CS01`.
    pub form_type: ChFormType,
    /// CH's human-readable description.
    pub description: String,
    /// ISO-8601 date (`YYYY-MM-DD`); optional.
    pub filed_on: Option<String>,
    /// Link to the filed document's metadata (when a document exists).
    pub document_metadata_url: String,
    /// The full original CH item.
    #[column(type = json)]
    pub raw: toasty::Json<serde_json::Value>,
    /// RFC 3339 UTC — when this row was last written by a fetch.
    pub fetched_at: String,
}

/// A filed accounts balance sheet parsed from Companies House (spec:
/// ch-filings-sync-spec.md §1, §6a). One row per `(company_id, period_end)`;
/// the `figures` column is the single filed period's line items in the
/// `PreviousYearFigures` shape.
#[derive(Debug, Serialize, Model)]
pub struct BalanceSheet {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub company_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = company_id, references = id)]
    pub company: toasty::Deferred<Company>,
    /// ISO-8601 date (`YYYY-MM-DD`) — the period end of the filed accounts.
    pub period_end: String,
    /// ISO-8601 date (`YYYY-MM-DD`); optional.
    pub filed_on: Option<String>,
    /// The `filings` row this balance sheet was parsed from.
    pub source_filing_id: Option<uuid::Uuid>,
    #[column(type = json)]
    pub figures: toasty::Json<reports::reports::uk_frs105_accounts::PreviousYearFigures>,
    /// The downloaded document, as received (zipped iXBRL, HTML, or PDF).
    pub raw_document: Option<Vec<u8>>,
    /// The parsed iXBRL document (the `.html` extracted from the download).
    pub parsed_document: Option<String>,
    /// RFC 3339 UTC.
    pub created_at: String,
}

#[derive(Debug, Serialize, Model)]
pub struct Ledger {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub company_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = company_id, references = id)]
    pub company: toasty::Deferred<Company>,
    /// Original upload filename.
    pub name: String,
    /// Absolute path of the stored file under the uploads dir.
    pub file_path: String,
    pub file_sha256: String,
    /// RFC 3339 UTC.
    pub uploaded_at: String,
    pub accounts_count: i64,
    pub transactions_count: i64,
    pub splits_count: i64,
    #[serde(skip)]
    #[has_many]
    pub accounts: toasty::Deferred<Vec<Account>>,
    #[serde(skip)]
    #[has_many]
    pub transactions: toasty::Deferred<Vec<Transaction>>,
    #[serde(skip)]
    #[has_many]
    pub splits: toasty::Deferred<Vec<Split>>,
}

#[derive(Debug, Serialize, Model)]
pub struct Account {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub ledger_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = ledger_id, references = id)]
    pub ledger: toasty::Deferred<Ledger>,
    pub guid: String,
    pub name: String,
    #[serde(rename = "type")]
    pub account_type: String,
    pub parent_guid: String,
    /// Balance as a decimal string (kept in sync with the splits on ingest).
    pub balance: rust_decimal::Decimal,
}

#[derive(Debug, Serialize, Model)]
pub struct Transaction {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub ledger_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = ledger_id, references = id)]
    pub ledger: toasty::Deferred<Ledger>,
    pub guid: String,
    /// RFC 3339 UTC (converted from the book's `chrono::NaiveDateTime`).
    pub post_datetime: String,
    /// GnuCash transaction description/memo ("" when the book has none).
    pub description: String,
}

#[derive(Debug, Serialize, Model)]
pub struct Split {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[index]
    pub ledger_id: uuid::Uuid,
    #[serde(skip)]
    #[belongs_to(key = ledger_id, references = id)]
    pub ledger: toasty::Deferred<Ledger>,
    #[index]
    pub tx_guid: String,
    #[index]
    pub account_guid: String,
    /// Value as a decimal string.
    pub value: rust_decimal::Decimal,
}
